Add gpg verification (Issue #29)
caddyserver/getcaddy.com pull request #35
Opened 2017-07-21 07:07 UTC by pepa65

2017-07-21 14:55 UTC, mholt requested changes
Thanks Pepa! This is cool. Also, does it remove the signature file after the install/update is done?

2017-07-21 14:55 UTC, mholt commented on index.txt
> +#             tar (or unzip on OSX and Windows)
Clarify that gpg is optional, if present it will verify signatures

2017-07-21 14:55 UTC, mholt commented on index.txt
> +		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $caddy_pgp >/dev/null 2>&1
Perhaps it would be better to get the key from Keybase directly?

2017-07-21 14:55 UTC, mholt commented on index.txt
> +		echo "Download verification not possible if gpg is not installed"
Change this text to say "Notice: download verification not possible because gpg is not installed" (makes a little more sense out of context)

2017-07-21 17:28 UTC, pepa65 commented on index.txt
> +		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $caddy_pgp >/dev/null 2>&1
I had that first, but it introduces a more fragile process I think, as the signature is shorter, and the keybase another party, and gpg still needs to be invoked to import the key. I think this is cleaner -- unless I misunderstand the process.

2017-07-21 17:30 UTC, pepa65 commented
Good point about deleting the signature file, intended to do that but forgot.

2017-07-21 18:33 UTC, mholt commented on index.txt
> +		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $caddy_pgp >/dev/null 2>&1
Okay, we'll go with that for now then

2017-07-21 18:33 UTC, mholt approved these changes

2017-07-21 18:34 UTC, mholt commented
I'll wait for @MatthewVance to review and then merge

2017-07-22 01:11 UTC, MatthewVance commented
This looks good. I also did a quick test in Docker container (Debian Jessie). @pepa65 thanks for implementing this. I tend to agree with that ha.pool.sks-keyservers.net may be better. It may also be more resilient since it's a pool of servers.

2017-08-10 17:46 UTC, merged